services:
    api:
        container_name: dd_api
        build:
            context: ../api
            dockerfile: dockerfile
        ports:
            - "8000:8000"
        env_file:
            - ./env/dev.env
        volumes:
            - ../api:/app